### PR TITLE
Forgot one Thing For the badges Link

### PR DESCRIPTION
**Pull request by TheBaconSpace**

### CODE REVIEW

**Comment by ttaylorr** [comment]
Looks great! Thanks for this catch. Could we maybe change the `Twitter` to `twitter` in the link URL that you changed?

**Comment by TheBaconSpace** [comment]
ill make a another pr 
@ttaylorr

**Comment by TheBaconSpace** [comment]
btw this is the only Thing i can Help with Beam Since #BeamLove

**Comment by ttaylorr** [comment]
Looks great, thanks! 👍

**Pull request merged**
